FROM node:12.16-alpine

RUN mkdir -p /usr/src/app

RUN apk --no-cache add --virtual builds-deps build-base python

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

CMD ["npm", "run", "dev"]